### ISSUE TITLE
Allow closing search bar with escape

### ISSUE THREAD

**Issue by jackwilsdon** [parcifal/expres#1]
Currently the search bar can only be closed using the `x` button, is it possible to allow Escape to be used as well?

**Comment by michaelvandeweerd** [comment]
At the moment you can close the _RE Search Bar_ using the close button and the key combination that is also used to display the bar, which is `ctrl` + `F` by default (customisable in the options page). Your suggestion will be taken into consideration for the next update as it does add an intuitive feature.
